theme = "awesome-identity"
baseURL = "https://cmol.github.io"
title = "Claus Lensbøl - Telecommunications engineer"


## Profile Configurations
[params.profile]
  portrait = "/images/cmol-square.png"
  firstname = "Claus"
  lastname = "Lensbøl"
  title = "Software design engineer / telecommunications engineer"
  #bio = """John Smith brings over 40 years experience leading, contributing to, and growing engineering organizations in top [**VR**](https://en.wikipedia.org/wiki/Virtual_reality) technology companies.
#
  #Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas et lacinia metus. Aliquam venenatis, orci ornare mollis congue, mi arcu lobortis tellus, id pulvinar ex ante eu mauris.
#
#  Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae.
#  """
  bio = """
  Claus Lensbøl is a collaborative engineer with a flair for all things internet and their implementations.

  A strong background in Linux and experience working with digital communication in various ways.

  Interests lie in complex networks, mobile communication, OpenSource development, maker spaces, network protocols, and data mining.

  Good theoretical background, but not afraid of practical work. Works great independently as well as in teams. Social and outgoing.
  """

[params.contacts]
  email = "cmol@cmol.dk"
  github = "cmol"
  twitter = "lensboel"
  #facebook = "john.smith"
  linkedin = "lensboel"
  #instagram = "john.smith"
  #stackoverflow = "7919458"
  keybase = "cmol"
  #medium = "john.smith"

## Footer Configurations
[params.footer]
  copyright = "© 2019 Claus Lensbøl. [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)."
  poweredBy = true
