theme = "awesome-identity"
baseURL = "https://cmol.me"
title = "Claus Lensbøl - Telecommunication Software Engineer"


## Profile Configurations
[params.profile]
  portrait = "/images/claus-cols.jpg"
  firstname = "Claus"
  lastname = "Lensbøl"
  title = "Telecommunication Software Engineer"
  #bio = """John Smith brings over 40 years experience leading, contributing to, and growing engineering organizations in top [**VR**](https://en.wikipedia.org/wiki/Virtual_reality) technology companies.
#
  #Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas et lacinia metus. Aliquam venenatis, orci ornare mollis congue, mi arcu lobortis tellus, id pulvinar ex ante eu mauris.
#
#  Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae.
#  """
  bio = """
  Experienced Software Engineer specializing in Linux, networking, and digital communication systems. Strong expertise in designing and
  optimizing complex system, from high speed network testers to Canadian banking integrations. Passionate about OpenSource, network protocols,
  real‑time synchronization, and multicast networking. Combines deep theoretical knowledge with hands‑on implementation, delivering scalable
  and efficient solutions. Works effectively both independently and in teams, bringing a collaborative and proactive approach.
  """

[params.contacts]
  email = "cmol@cmol.dk"
  github = "cmol"
  twitter = "lensboel"
  #facebook = "john.smith"
  linkedin = "lensboel"
  #instagram = "john.smith"
  #stackoverflow = "7919458"
  keybase = "cmol"
  medium = "@lensboel"

[params.actions.blog]
  url  = "/files/cv.pdf"
  name = "Review my CV"
[params.actions.click]
  url  = "https://blog.cmol.me"
  name = "Read my blog posts"
#[params.actions.clock]
#  url  = "https://cmol.me"
#  name = "tost"

## Footer Configurations
[params.footer]
  copyright = "© 2025 Claus Lensbøl. [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)."
  poweredBy = true
